{% set name = "airflow-code-editor" %}
{% set version = "7.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/airflow_code_editor-{{ version }}.tar.gz
  sha256: 4652d2c3ef475ed42a078bc8d222707c1deb77e314c268d3f08774bc283f3ea1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - apache-airflow
    - fs >=2.4.16
    - pss >=1.44

test:
  imports:
    - airflow_code_editor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andreax79/airflow-code-editor
  summary: Apache Airflow code editor and file manager
  license: Apache-2.0
  license_file:
    - LICENSE
    - airflow_code_editor/static/fonts/LICENSE

extra:
  recipe-maintainers:
    - xylar
    - rxm7706
